spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: 11280534

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

#drop-first=false:

#app:
#  server:
#    url: ${app.server.url}
